### ISSUE TITLE
Travis builds against multiple symfony versions

### ISSUE THREAD

**Issue by h4cc** [aequasi/cache-bundle#38]
How about letting travis build against multiple symfony versions?

Example configuration here: https://github.com/h4cc/AliceFixturesBundle/blob/master/.travis.yml

I could configure that if wished :)

**Comment by aequasi** [comment]
Go for it :)

**Comment by h4cc** [comment]
FYI: Your Tests did not run for some time, because tests/boostrap.php silently exited with 0 resolving the phpunit call successfully...

**Comment by h4cc** [comment]
Okay, building now against symfony 2.1 to 2.6. Using a phpunit from require-dev.

There seems to be a problem with symfony 2.1, maybe we just simple skip that because its not supported anymore and quite old too.

**Comment by aequasi** [comment]
heh, thats embarrassing. Yeah, lets version bump up to >=2.2.0,<3.0
