### ISSUE TITLE
Routing Caching with FOS Rest Bundle

### ISSUE THREAD

**Issue by csiewert** [aequasi/cache-bundle#43]
If you use fos/rest bundle and using routing caching from aequasi memcache bundle, the bundle does not stores the http verb to cache.

you have two routes:

- GET /user/profile
- PUT /user/profile

If you send a PUT without routing caching enabled, it jumps in the right method. If you send a PUT with routing caching enabled, it jumps in getUserProfile instead of putUserProfile.

It would be better, if you also cache the http verb: e.g.: get_user_profile, put_user_profile

**Comment by aequasi** [comment]
Care to throw in a pull request? I can do it, but its gonna take a bit

**Comment by csiewert** [comment]
Nah, I can do it. Thanks for responding.
