### ISSUE TITLE
disable memcache for one or two specific queries

### ISSUE THREAD

**Issue by alexloehner** [aequasi/cache-bundle#44]
Hello,

I've a great problem: on the one hand I really want and need speed thing up a little bit by using memcache in my symfony2 application. On the other hand I have at least one or two single queries I never want to be cached.

Any idea how to do that?

**Comment by aequasi** [comment]
Thats done by doctrine

http://doctrine-orm.readthedocs.org/en/latest/reference/caching.html#result-cache
