### ISSUE TITLE
symfoy3 support

### ISSUE THREAD

**Issue by joschua011** [aequasi/cache-bundle#57]
Cant install this bundle on symfony3:

~~~
composer update
....
- aequasi/cache-bundle 3.0.2 requires symfony/symfony ~2.2 -> no matching package found.
~~~

Any plans to support symfony3 soon?
Or how can i make composor ignore the dependency?

**Comment by Nyholm** [comment]
We have been working on https://github.com/php-cache/cache-bundle for a while now. Iris a update of this bundle and it supports psr6. 
That new versions supports 3.0 as far as I know.

**Comment by joschua011** [comment]
Thank you that bundle works on symfony3.

**Comment by Nyholm** [comment]
Awesome! 
I've just started to use the new cache bundle in production. Let me know if you find any issues or if you are missing some features.
