### ISSUE TITLE
aequasi/cache-bundle dev-master requires psr/cache-implementation ~1.0 -> no matching package found.

### ISSUE THREAD

**Issue by PaddyLock** [aequasi/cache-bundle#58]
When running composer install I get the following issue:

aequasi/cache-bundle dev-master requires psr/cache-implementation ~1.0 -> no matching package found.

**Comment by PaddyLock** [comment]
Is it related to this? https://github.com/tedious/Stash/issues/233

**Comment by Nyholm** [comment]
No, The error message tells you that you need to install a package that implements PSR6. 

Have a look at this bundle: https://github.com/php-cache/cache-bundle
It is under development but will replace the functionality from this bundle.
