### ISSUE TITLE
PHP requirement ~5.3

### ISSUE THREAD

**Issue by aferrandini** [aequasi/cache-bundle#59]
If you want to use or test the bundle with php 7.x, composer will fail with the following error.

```
- aequasi/cache-bundle 3.0.2 requires php ~5.3 -> your PHP version (7.0.8) does not satisfy that requirement.
```

**Comment by aequasi** [comment]
As mentioned in the readme, this bundle is deprecated, in favor of http://www.php-cache.com/. I won't be doing anything to upgrade this bundle. Sorry for any inconvenience.
