### ISSUE TITLE
Problem with composer

### ISSUE THREAD

**Issue by WarGot-by** [aequasi/cache-bundle#60]
Can someone tell me how to install using the composer version is available at https://github.com/aequasi/cache-bundle. 
There in the configuration indicates support php 7.0 https://github.com/aequasi/cache-bundle/blob/master/composer.json

When I run in console 
`
composer.phar require aequasi/cache-bundle
`
installed version 2.4 which not support php 7.0 -(

I have no way to switch to php-cache bundle -((

**Comment by Nyholm** [comment]
Have a look at php-cache.com and the [Symfony Bundles](http://www.php-cache.com/en/latest/symfony/cache-bundle/). There is PHP 7 support there. 

Also this bundle is deprecated: https://github.com/aequasi/cache-bundle#this-bundle-is-deprecated

**Comment by aequasi** [comment]
Thanks @Nyholm :)

@WarGot-by 
> I have no way to switch to php-cache bundle -((

What do you mean?

**Comment by WarGot-by** [comment]
@Nyholm @aequasi 
In the documentation it is written that bundle works with php versions below 7.1. 
When installed via composer the installed version requires php version 5.3.
How to install a version that works with php7 ? Or support php7 is not at all ?

**Comment by aequasi** [comment]
This bundle is deprecated. You need to move to php-cache. If you are having issues installing it, open an issue on the issue tracker over there.
